export const TEXT = 'TEXT';
export const IMAGE_REQUEST_PENDING ='IMAGE_REQUEST_PENDING';
export const IMAGE_REQUEST_SUCCESS ='IMAGE_REQUEST_SUCCESS';
export const IMAGE_REQUEST_FAILED ='IMAGE_REQUEST_FAILED';
export const MULTIPALEINPUT = 'MULTIPALEINPUT'
export const EMPTYINPUT = 'EMPTYINPUT'
export const RESET ='RESET';
export const DETECTED = 'DETECTED';

export const GETTINGIMAGE = 'GETTINGIMAGE';
export const RESETINPUTIMAGE = 'RESETINPUTIMAGE'