export const SENDING_EMAIL_PENDING = 'SENDING_EMAIL_PENDING'
export const SENDING_EMAIL_SUCCESS = 'SENDING_EMAIL_SUCCESS'
export const SENDING_EMAIL_FAILED = 'SENDING_EMAIL_FAILED'
export const VERIFIY_EMAIL_PENDING = 'VERIFIY_EMAIL_PENDING'
export const VERIFIY_EMAIL_SUCCESS = 'VERIFIY_EMAIL_SUCCESS'
export const VERIFIY_EMAIL_FAILED = 'VERIFIY_EMAIL_FAILED'

