// pages
export const GO_HOME='GO_HOME';
export const REGISTER = 'REGISTER';
export const SIGN_IN='SIGN_IN';
export const DEFAULT = 'DEFAULT';
//signin
export const SIGN_IN_EMAIL='SIGN_IN_EMAIL';
export const SIGN_IN_PASSWORD='SIGN_IN_PASSWORD';
export const SIGN_IN_DEFAULT='SIGN_IN_DEFAULT';
export const SIGN_IN_REMOVE_ERROR_MSG='SIGN_IN_REMOVE_ERROR_MSG';
export const REQUEST_PENDING= 'REQUEST_PENDING'
export const REQUEST_SUCCESS= 'REQUEST_SUCCESS'
export const REQUEST_FAILED= 'REQUEST_FAILED'
//register
export const REGISTER_EMAIL='REGISTER_EMAIL';
export const REGISTER_PASSWORD='REGISTER_PASSWORD';
export const REGISTER_NAME='REGISTER_NAME';
export const REGISTER_DEFAULT='REGISTER_DEFAULT';
//user information
export const USER_INFORMATION='USER_INFORMATION';
