// pages
export const REGISTER = 'REGISTER';
export const SIGN_IN='SIGN_IN';
//signin
export const SIGN_IN_EMAIL='SIGN_IN_EMAIL';
export const SIGN_IN_PASSWORD='SIGN_IN_PASSWORD';
export const SIGN_IN_DEFAULT='SIGN_IN_DEFAULT';
export const REMOVE_ERROR_MSG='REMOVE_ERROR_MSG';
export const REQUEST_PENDING= 'REQUEST_PENDING'
export const REQUEST_SUCCESS= 'REQUEST_SUCCESS'
export const REQUEST_FAILED= 'REQUEST_FAILED'
export const VERIFIY_EMAIL_SUCCESS = 'VERIFIY_EMAIL_SUCCESS'
export const VERIFIY_EMAIL_FAILED = 'VERIFIY_EMAIL_FAILED'
//register
export const REGISTER_EMAIL='REGISTER_EMAIL';
export const REGISTER_PASSWORD='REGISTER_PASSWORD';
export const REGISTER_NAME='REGISTER_NAME';
export const REGISTER_DEFAULT='REGISTER_DEFAULT';
